#	This file is derived from ToolFactory JVM driver.                 
#	                                                                  
#	Hosted at: https://github.com/toolfactory/jvm-driver              
#	                                                                  
#	Modified by: Roberto Gentili                                      
#	                                                                  
#	Modifications hosted at: https://github.com/burningwave/jvm-driver                                                            
#	                                                                                                            
#	- -                                                                                                          
#	                                                                                                            
#	The MIT License (MIT)                                                                                       
#	                                                                                                            
#	Copyright (c) 2019-2022 Luke Hutchison, Roberto Gentili                                                            
#	                                                                                                            
#	Permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated
#	documentation files (the "Software"), to deal in the Software without restriction, including without        
#	limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of   
#	the Software, and to permit persons to whom the Software is furnished to do so, subject to the following    
#	conditions:                                                                                                 
#	                                                                                                            
#	The above copyright notice and this permission notice shall be included in all copies or substantial        
#	portions of the Software.                                                                                   
#	                                                                                                            
#	THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING BUT NOT       
#	LIMITED TO THE WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO   
#	EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN
#	AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE
#	OR OTHER DEALINGS IN THE SOFTWARE.
#
name: Build and release if requested



on:
  push:
    branches:
      - main
    paths:
      - "**.sh"
      - "**.cmd"
      - "**.c"
      - "**.cpp"
      - "**.java"
      - ".github/workflows/**"
      - "**.properties"
      - "**.xml"



jobs:
   
  aarch64_job:
    # The host should always be Linux
    runs-on: ubuntu-18.04
    name: Build on ubuntu-18.04 armv7
    steps:
      - uses: actions/checkout@v2.1.0
      - uses: actions/setup-java@v2.5.0
        with:
          java-version: ${{ matrix.java }}
          distribution: 'zulu'
          architecture: 'aarch64'
      - uses: uraimo/run-on-arch-action@v2
        name: Run commands
        id: runcmd
        with:
          arch: 'aarch64'
          distro: ubuntu18.04
          run: |
            run: mvn -B clean compile -Dproject_jdk_version=${{ matrix.java }} -DskipTests=true --file ./native/pom.xml
